#! /bin/bash

echo "LISP-like to Standard ML of New Jersey v110.79 [built: Tue Aug  8 23:21:20 2017]"
echo "Type a lisp like command, press Ctrl-C to exit"

while true;
do

input=$(rlwrap -p -S '- ' -H stack -o cat)
#read -p '- ' input

exp="val exp = ""$input"";"
eval_exp="eval exp;"

echo $exp >> interprete.sml
echo $eval_exp >> interprete.sml

(sml < interprete.sml) > foo

bar=$(tail -2 foo | head -1 | awk -F" " '{print $4}')

bar="${bar%\"}"
bar="${bar#\"}"
bar="${bar//\\}"

echo $bar > tmp

#cat tmp

(sml < tmp) > foo

tail -n +2 foo | head -1 > tmp; mv tmp foo
tail -2 foo | awk -F" " '{$2=""; print $0}' | awk -F" " '{$1=$1} 1'

head -n -2 interprete.sml > tmp; mv tmp interprete.sml
rm foo
echo

done
